DATA SEGMENT PARA PUBLIC 'DATA'
    VAR1    DW    1234H
    VAR2    DW    0ABCDH
    VAR3    DW    5412H
    VAR4    DW    5F3EH
    RES     DQ    ?
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
PUSH DS
XOR AX, AX
MOV DS, AX
PUSH AX
MOV AX, DATA
MOV DS, AX
; your code starts here
PUSH VAR1
PUSH VAR2
PUSH VAR3
PUSH VAR4

POP WORD PTR RES[6]
POP WORD PTR RES[4]
POP WORD PTR RES[2]
POP WORD PTR RES[0]
; your code ends here
RET
START ENDP

CODE ENDS
END START
