DATA SEGMENT PARA PUBLIC 'DATA'
    ORG     02ACH
    VAR1    DW  4567H
    VAR2    DD  ?
DATA ENDS

DATA2 SEGMENT PARA PUBLIC 'DATA'
    ORG     0A01H
    VAR3    DW  ?
    VAR4    DD  1200AB00H
DATA2 ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
PUSH DS
XOR AX, AX
MOV DS, AX
PUSH AX
MOV AX, DATA
MOV DS, AX
; your code starts here

; your code ends here
RET
START ENDP

CODE ENDS
END START