DATA SEGMENT PARA PUBLIC 'DATA'
    NUMBER  DD  12AB34CDH
    NB_STR  DB  $-NUMBER DUP ('')
    TTABLE   DB  '0123456789ABCEDF'
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
PUSH DS
XOR AX, AX
MOV DS, AX
PUSH AX
MOV AX, DATA
MOV DS, AX
; your code starts here

; your code ends here
RET
START ENDP

CODE ENDS
END START