DATA SEGMENT PARA PUBLIC 'DATA'
    VEC     DB  8, 'asm.lng_'
    ; VEC[0] -> holds the length of the vector
    ; VEC[1] - VEC[8] -> the elements of the vector
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
PUSH DS
XOR AX, AX
MOV DS, AX
PUSH AX
MOV AX, DATA
MOV DS, AX
; your code starts here
PUSH OFFSET VEC
CALL UPPER
ADD SP, 2
; your code ends here
RET
START ENDP
CODE ENDS

CODE2 SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE2

; Procedure definition
UPPER PROC FAR

RET
UPPER ENDP

CODE2 ENDS

END START