DATA SEGMENT PARA PUBLIC 'DATA'
    VEC     DB      5, 15, 21, 98, 32, 17, 29
    LEN     DB      $ - VEC
    NUM     DB      7
DATA ENDS

EXTRN REPLACE_ODD:FAR

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
PUSH DS
XOR AX, AX
MOV DS, AX
PUSH AX
MOV AX, DATA
MOV DS, AX
; your code starts here
PUSH OFFSET VEC
PUSH OFFSET LEN
PUSH OFFSET NUM
CALL REPLACE_ODD
; your code ends here
RET
START ENDP
CODE ENDS
END START